export {default as Home} from "./Home"
export {default as PlanTrip} from "./PlanTrip"
export {default as Discover} from "./Discover"
export {default as Login} from "./Login"
export {default as Signup} from "./Signup"